language: python

python:
  - "2.7"
  - "3.6"

env:
  global:
    - BLUEZ_SRC_DIR="./contrib/bluez"
    - LOCAL_INCLUDE_DIR="./include"

os:
  - linux

before_install:
  
  - git clone https://git.kernel.org/pub/scm/bluetooth/bluez.git -n $BLUEZ_SRC_DIR && cd $BLUEZ_SRC_DIR && git checkout $(git describe --tags $(git rev-list --tags='[0-9]*.[0-9]*' -n 1)) && cd -
  - mkdir -p $LOCAL_INCLUDE_DIR/bluetooth && cp $BLUEZ_SRC_DIR/lib/*.h $LOCAL_INCLUDE_DIR/bluetooth
  - wget http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.gz && tar -xvzf boost_1_58_0.tar.gz && cd boost_1_58_0 && ./bootstrap.sh && sudo ./b2 install && cd -
  - pip install -r requirements.txt

install:
  - CFLAGS="-I$LOCAL_INCLUDE_DIR" python setup.py build
  - pip install .[ble]

script:
  - python examples/simple/inquiry.py || true

# Use VMs instead of Docker; bluez is not on the approved package whitelist
# https://github.com/travis-ci/apt-package-whitelist/issues/2463
sudo: true

addons:
  apt:
    packages:
      - bluez
      - libbluetooth-dev
      - pkg-config
      - libglib2.0-dev
      - python-dev
